### ISSUE TITLE
Set up React context

### ISSUE THREAD

**Issue by SphericalKat** [GDGVIT/recruitments-portal-2020#13]
We intend to use the context for maintaining global themes and user credentials.

**Comment by abdimohamud** [comment]
Hope this helps for login/authenication: https://codesandbox.io/s/login-authentication-usecontext-66t9t?file=/src/Config/routes.js

and by the way, if your open to maybe using a different approach on global themes, I'd highly reccomend using SCSS and creating a global style sheet thats consistent throughout the app sort of like this : https://codesandbox.io/s/ecstatic-cherry-squty

**Comment by SphericalKat** [comment]
Thanks for the examples @abdimohamud, I'll take a look at using sass/scss.
